server:
  port: 8088

spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:${CLASSPATH}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET_KEY}

  devtools:
    restart:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: mtins829@gmail.com
    password: kgb501511
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one-team-SA-proj?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password:
web:
  resources:
    static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo
custom:
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo
  siteName: kicknalisys
  siteMainUri: http://localhost:8088
  emailFrom: no-reply@localhost
  emailFromName: kicknalisys
  genFileDirPath: C:\work_oneteam\one-team-SA-proj\images