server:
  port: 8088
  servlet:
    session:
      persistent: false

spring:
  profiles:
    active: dev
    include: secret

  devtools:
    restart:
      enabled: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one-team-SA-proj?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password:

web:
  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo

custom:
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo
  siteName: kicknalisys
  siteMainUri: http://localhost:8088
  emailFrom: Kicknalisys Support Team
  emailFromName: kicknalisys
  uploadDir: C:/work_oneteam/one-team-SA-proj/src/main/resources/static/images
  genFileDirPath: C:\work_oneteam\one-team-SA-proj\images
  videoFileDirPath: C:\work_oneteam\one-team-SA-proj\videos
logging:
  level:
    logging.level.org.springframework.security: DEBUG