server:
  port: 8088

spring:
  profiles:
    include: secret

  devtools:
    restart:
      enabled: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

web:
  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo

custom:
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo
  siteName: kicknalisys
  siteMainUri: http://localhost:8088
  emailFrom: no-reply@localhost
  emailFromName: kicknalisys
  genFileDirPath: C:\work_oneteam\one-team-SA-proj\images
  videoFileDirPath: C:\work_oneteam\one-team-SA-proj\videos
logging:
  level:
    logging.level.org.springframework.security: DEBUG