server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/one-team-SA-proj
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

custom:
  type-aliases-package: com.lyj.proj.oneteamsaproj.vo
  siteName: kicknalisys
  siteMainUri: https://www.kicknalysis.ygcqwe.site
  emailFrom: no-reply@localhost
  emailFromName: kicknalisys
  genFileDirPath: /app/files/images
  videoFileDirPath: /app/files/videos